spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb?TimeZone=UTC
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  
  kafka:
    bootstrap-servers: localhost:9092
