server:
  port: 8083

spring:
  application:
    name: product-service
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecureSecretKeyForJWT1234567890123456789012345678901234567890}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Kolkata} [%thread] %-5level %logger{36}.%M(%F:%L) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Kolkata} [%thread] %-5level %logger{36}.%M(%F:%L) - %msg%n"
  level:
    root: INFO
    com.example: DEBUG
    org:
      springframework:
        web: INFO
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
