spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb?TimeZone=UTC
    username: dev
    password: dev

  kafka:
    bootstrap-servers: localhost:9092

product-service:
  url: http://localhost:8083

inventory-service:
  url: http://localhost:8085
